### PR TITLE
multi-instance for osTicket 1.17+

### PR DESCRIPTION
**Pull request by Cartmega**
We have modified autocloser to comply with osTicket 1.17 multi-instance capabilities. This allows the plugin to be configured with as many configurations as needed. Various issues with the original version have also been fixed.

### CODE REVIEW

**Comment by Cartmega** [comment]
Done!

**Comment by HairyDuck** [comment]
@Cartmega Do you think you could make these changes to https://github.com/clonemeagain/osticket-plugin-responder as well?

**Comment by Cartmega** [comment]
> @Cartmega Do you think you could make these changes to https://github.com/clonemeagain/osticket-plugin-responder as well?

I could, but time is slim atm. I am sure if you know a bit of PHP you could follow the changes I made and apply them to the other plugin with some effort.

**Comment by HairyDuck** [comment]
> 

Errrrrrr can try. I'll let you know how I get on.

**Comment by Cartmega** [comment]
If you find difficulty I will try to help you out.

**Comment by HairyDuck** [comment]
It took me a while to get around to it but I think I got it sorted.
https://github.com/clonemeagain/osticket-plugin-responder/pull/7

**Pull request merged**
